### ISSUE TITLE
Todo list @gmocciaro

### ISSUE THREAD

**Issue by gmocciaro** [uomars/UOMars#425]
- [x] Usher Neutral
- [x] Usher PK
- [x] Usher Chaos
- [x] Usher Order
- [x] Region Neutral
- [x] Region PK
- [x] Region Chaos
- [x] Region Order
- [x] Remap Outposts
- [x] Region Outpost -> https://github.com/uomars/UOMars/issues/411
- [x] Test Linking con forum e cambio password
- [x] Controllare comportamento case al delete dell'account
- [x] Test evento (una città qualsiasi)
- [x] Test "evento" Outpost (attacco, conquista, protezione) - RIMANE DA TESTARE PROTEZIONE
- [x] Aggiungere informazione su item exceptional nel propertyList
- [x] Avvisi alla region outpost (e alla città) quando viene conquistato un outpost
- Volcano
  - [x] FInire gump ridotto (fine evento)
  - [x] Inserire broadcast globali (su timing evento)
  - [x] Creazione lista statica con membri attivi (tempo di "possessione" delle flag)
  - [x] Distribuzione premi in denaro
  - [x] Distribuzione premi partecipazione
  - [x] Comunicazione del recap nel sito
  - [x] Conteggio morti durante l'evento
  - [x] Bug after save (deserialize): non è possibile rubare le bandiere
  - [x] check region per il res se deve tornare alla base
  - [x] HTML recap evento con morti, tempo flag, flag bruciate
  - [x] TESTARE
  - [x] Fixare bug costruttore exp ticket
  - [x] Bilanciare con Ale in base ai dati di https://uomars.it/volcano-events/?e=70
 - [x] Disarmare al cambio skill da .caps
 - [x] remap dropzone volcano -> https://github.com/uomars/UOMars/issues/454
 - [x] Fix res potions -> https://github.com/uomars/UOMars/issues/443
 - [x] Progression sul premium -> https://github.com/uomars/UOMars/issues/491

**Comment by Ale1991** [comment]
pushato tutte le region per gli outpost:
- EnigmaOutpost
- EdictoOutpost
- ConfusioOutpost
- DragonOutpost
manca l'avamposto worker alle lostland (sia la classe lato codice che le coordinate che vanno recuperate da centred)

**Comment by morpheus8888** [comment]
inserisco qui per ricordarcelo di gasce

**Comment by SampinoInfernal** [comment]
gasce cmq è ancora down

**Comment by gmocciaro** [comment]
ancora non si è deciso cosa dare come premio partecipazione
